export const boxscoreResults = {
  "三　振": "strikeOuts",
  "振　逃": "strikeOuts",
  "四　球": "baseOnBalls",
  "敬遠四": "intentionalWalks",
  "死　球": "hitByPitch",

  "投　２": "doubles",
  "一　２": "doubles",
  "二　２": "doubles",
  "三　２": "doubles",
  "遊　２": "doubles",
  "左　２": "doubles",
  "中　２": "doubles",
  "右　２": "doubles",
  "左中２": "doubles",
  "右中２": "doubles",
  "右線２": "doubles",
  "左線２": "doubles",
  "右越２": "doubles",
  "中越２": "doubles",
  "左越２": "doubles",
  "左エ２": "doubles",
  "中エ２": "doubles",
  "右エ２": "doubles",

  "左中３": "triples",
  "右中３": "triples",
  "左越３": "triples",
  "中越３": "triples",
  "右越３": "triples",
  "左　３": "triples",
  "中　３": "triples",
  "右　３": "triples",
  "左線３": "triples",
  "右線３": "triples",

  "左越本": "homeRuns",
  "中越本": "homeRuns",
  "右越本": "homeRuns",
  "左中本": "homeRuns",
  "右中本": "homeRuns",

  "投　飛": "popOuts",
  "捕　飛": "popOuts",
  "一　飛": "popOuts",
  "二　飛": "popOuts",
  "三　飛": "popOuts",
  "遊　飛": "popOuts",
  "左　飛": "flyOuts",
  "中　飛": "flyOuts",
  "右　飛": "flyOuts",

  "投邪飛": "popOuts",
  "捕邪飛": "popOuts",
  "一邪飛": "popOuts",
  "二邪飛": "popOuts",
  "三邪飛": "popOuts",
  "遊邪飛": "popOuts",
  "左邪飛": "flyOuts",
  "中邪飛": "flyOuts",
  "右邪飛": "flyOuts",

  "捕飛失": "x-popOuts",
  "投飛失": "x-popOuts",
  "一飛失": "x-popOuts",
  "二飛失": "x-popOuts",
  "三飛失": "x-popOuts",
  "遊飛失": "x-popOuts",
  "左飛失": "x-flyOuts",
  "中飛失": "x-flyOuts",
  "右飛失": "x-flyOuts",

  "左犠飛": "sacFlies",
  "中犠飛": "sacFlies",
  "右犠飛": "sacFlies",

  "投犠打": "sacBunts",
  "捕犠打": "sacBunts",
  "一犠打": "sacBunts",
  "二犠打": "sacBunts",
  "三犠打": "sacBunts",
  "遊犠打": "sacBunts",

  "投犠野": "sacBunts",
  "捕犠野": "sacBunts",
  "一犠野": "sacBunts",
  "二犠野": "sacBunts",
  "三犠野": "sacBunts",
  "遊犠野": "sacBunts",

  "投犠失": "sacBunts",
  "捕犠失": "sacBunts",
  "一犠失": "sacBunts",
  "二犠失": "sacBunts",
  "三犠失": "sacBunts",
  "遊犠失": "sacBunts",

  "投捕一二三遊左中右": "x-flyOuts",

  "投　直": "lineOuts",
  "捕　直": "lineOuts",
  "一　直": "lineOuts",
  "二　直": "lineOuts",
  "三　直": "lineOuts",
  "遊　直": "lineOuts",
  "左　直": "lineOuts",
  "中　直": "lineOuts",
  "右　直": "lineOuts",

  "投邪直": "lineOuts",
  "捕邪直": "lineOuts",
  "一邪直": "lineOuts",
  "二邪直": "lineOuts",
  "三邪直": "lineOuts",
  "遊邪直": "lineOuts",
  "左邪直": "lineOuts",
  "中邪直": "lineOuts",
  "右邪直": "lineOuts",

  "投直失": "x-lineOuts",
  "捕直失": "x-lineOuts",
  "一直失": "x-lineOuts",
  "二直失": "x-lineOuts",
  "三直失": "x-lineOuts",
  "遊直失": "x-lineOuts",
  "左直失": "x-lineOuts",
  "中直失": "x-lineOuts",
  "右直失": "x-lineOuts",

  "投ゴロ": "groundOuts",
  "捕ゴロ": "groundOuts",
  "一ゴロ": "groundOuts",
  "二ゴロ": "groundOuts",
  "三ゴロ": "groundOuts",
  "遊ゴロ": "groundOuts",
  "左ゴロ": "groundOuts",
  "中ゴロ": "groundOuts",
  "右ゴロ": "groundOuts",

  "投ゴ失": "errors",
  "捕ゴ失": "errors",
  "一ゴ失": "errors",
  "二ゴ失": "errors",
  "三ゴ失": "errors",
  "遊ゴ失": "errors",

  "投飛失": "errors",
  "捕飛失": "errors",
  "一飛失": "errors",
  "二飛失": "errors",
  "三飛失": "errors",
  "遊飛失": "errors",
  "左飛失": "errors",
  "中飛失": "errors",
  "右飛失": "errors",

  "投直失": "errors",
  "捕直失": "errors",
  "一直失": "errors",
  "二直失": "errors",
  "三直失": "errors",
  "遊直失": "errors",
  "左直失": "errors",
  "中直失": "errors",
  "右直失": "errors",

  "投野選": "x-groundOuts",
  "捕野選": "x-groundOuts",
  "一野選": "x-groundOuts",
  "二野選": "x-groundOuts",
  "三野選": "x-groundOuts",
  "遊野選": "x-groundOuts",

  "投併打": "groundOuts",
  "捕併打": "groundOuts",
  "一併打": "groundOuts",
  "二併打": "groundOuts",
  "三併打": "groundOuts",
  "遊併打": "groundOuts",

  "投併失": "errors",
  "捕併失": "errors",
  "一併失": "errors",
  "二併失": "errors",
  "三併失": "errors",
  "遊併失": "errors",

  "投　安": "x-hits",
  "捕　安": "x-hits",
  "一　安": "x-hits",
  "二　安": "x-hits",
  "三　安": "x-hits",
  "遊　安": "x-hits",

  "投バ安": "x-hits",
  "捕バ安": "x-hits",
  "一バ安": "x-hits",
  "二バ安": "x-hits",
  "三バ安": "x-hits",
  "遊バ安": "x-hits",

  "左前安": "x-hits",
  "中前安": "x-hits",
  "右前安": "x-hits",
  "左越安": "x-hits",
  "中越安": "x-hits",
  "右越安": "x-hits",
  "左線安": "x-hits",
  "右線安": "x-hits",

  "打妨出": "x-catchersInterference",
}
